"use client";

import { useActionState } from "react";
import { IDLE_FORM_STATE, type AdminFormState } from "@/lib/admin/forms";
import { Field, controlClass, textareaClass } from "@/components/admin/field";
import { FormFeedback, SubmitButton } from "@/components/admin/form-controls";

/**
 * Search and sharing overrides.
 *
 * A separate form from the main record, because these are optional overrides
 * rather than part of the thing itself — and because saving them should not
 * require re-submitting a price.
 *
 * There is no "expose this draft" risk to guard against here (§17). Metadata is
 * generated by the public route, which only ever loads PUBLISHED records via
 * PUBLIC_PRODUCT_WHERE; a draft has no page for metadata to appear on. Filling
 * these in early is how the team prepares a launch, not a leak.
 */
export function SeoForm({
  action,
  id,
  values,
  fallbackTitle,
  fallbackDescription,
  mediaField,
}: {
  action: (previous: AdminFormState, formData: FormData) => Promise<AdminFormState>;
  id: string;
  values: { seoTitle: string; seoDescription: string };
  fallbackTitle: string;
  fallbackDescription: string;
  /** The OG image control, rendered by the server so it can load media rows. */
  mediaField: React.ReactNode;
}) {
  const [state, formAction] = useActionState(action, IDLE_FORM_STATE);
  const errors = state.errors ?? {};

  return (
    <form action={formAction} className="flex flex-col gap-5">
      <input type="hidden" name="id" value={id} />

      <Field
        name="seoTitle"
        label="Search title"
        error={errors.seoTitle}
        hint="Around 60 characters"
        help={`Leave blank to use “${fallbackTitle}”.`}
      >
        {(props) => (
          <input
            {...props}
            type="text"
            maxLength={120}
            defaultValue={values.seoTitle}
            placeholder={fallbackTitle}
            className={controlClass}
          />
        )}
      </Field>

      <Field
        name="seoDescription"
        label="Meta description"
        error={errors.seoDescription}
        hint="Around 155 characters"
        help={
          fallbackDescription
            ? "Leave blank to use the description above."
            : "There is no description to fall back on, so search results will show whatever the search engine picks."
        }
      >
        {(props) => (
          <textarea
            {...props}
            maxLength={320}
            defaultValue={values.seoDescription}
            className={textareaClass}
          />
        )}
      </Field>

      {mediaField}

      <div className="flex flex-wrap items-center gap-4">
        <SubmitButton size="sm" variant="outline">
          Save search settings
        </SubmitButton>
        <FormFeedback state={state} />
      </div>
    </form>
  );
}
